#ifndef SPINE_SPINE_TEXTURE_FILTER_H
#define SPINE_SPINE_TEXTURE_FILTER_H


typedef enum {
    SPINE_TEXTURE_FILTER_UNKNOWN = 0,
    SPINE_TEXTURE_FILTER_NEAREST,
    SPINE_TEXTURE_FILTER_LINEAR,
    SPINE_TEXTURE_FILTER_MIP_MAP,
    SPINE_TEXTURE_FILTER_MIP_MAP_NEAREST_NEAREST,
    SPINE_TEXTURE_FILTER_MIP_MAP_LINEAR_NEAREST,
    SPINE_TEXTURE_FILTER_MIP_MAP_NEAREST_LINEAR,
    SPINE_TEXTURE_FILTER_MIP_MAP_LINEAR_LINEAR
} spine_texture_filter;



#endif /* SPINE_SPINE_TEXTURE_FILTER_H */
